# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-16 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shuup', '0013_product_shipping_mode_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalbitcoinsCheckoutPaymentProcessor',
            fields=[
                ('paymentprocessor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shuup.PaymentProcessor')),
                ('api_key', models.CharField(max_length=150, verbose_name='API Key')),
                ('api_secret', models.CharField(max_length=150, verbose_name='API Secret')),
            ],
            options={
                'abstract': False,
            },
            bases=('shuup.paymentprocessor',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
