# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-18 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_localbitcoins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localbitcoinscheckoutpaymentprocessor',
            name='accept_zero_conf',
            field=models.BooleanField(default=True, verbose_name='Accept zero confirmation payments'),
        ),
    ]
